### PR TITLE
Android Build Crash issue fixed.

### PR DESCRIPTION
**Pull request by ponikar**
There was mismatched Theme type in ScrollView Constructor. 

We are using this library and it is working completely fine.

### CODE REVIEW

**Comment by friedolinfoerder** [comment]
Hi, what version of React Native do you use?

**Comment by ponikar** [comment]
0.65.1

**Comment by friedolinfoerder** [comment]
I think the reason for the crash is the different React Native version. We currently use 0.69.4 and there `android.content.Context` is fine.

**Comment by ponikar** [comment]
We can still update the doc for providing support older than the 0.69 version.

**Comment by friedolinfoerder** [comment]
Good point 👍 I updated the readme.

**Pull request closed without merging**
